[package]
name = "ebpf-rust-poc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = { workspace = true, features = ["async_tokio"] }
aya-log = { workspace = true }
ebpf-rust-poc-common = { path = "../ebpf-rust-poc-common", features = ["user"] }
anyhow = "1"
clap = { version = "4.1", features = ["derive"] }
log = "0.4"
tokio = { version = "1.25", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "net",
  "signal",
] }
env_logger = "0.11"
opentelemetry = { version = "0.29.1", features = ["metrics", "trace"] }
opentelemetry_sdk = { version = "0.29.0", features = ["metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.29.0", features = ["trace", "metrics"] }
opentelemetry-semantic-conventions = { version = "0.10.0" }
opentelemetry-proto = { version = "0.1.0"}
opentelemetry-stdout = { version = "0.29.0", features = ["metrics"] }

[build-dependencies]
aya-build = { workspace = true }
anyhow = "1"

ebpf-rust-poc-ebpf = { path = "../ebpf-rust-poc-ebpf" }

[[bin]]
name = "ebpf-rust-poc"
path = "src/main.rs"