apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-rust-poc-pod
  namespace: kube-system
  labels:
    app: ebpf-rust-poc
spec:
  selector:
    matchLabels:
      app: ebpf-rust-poc
  template:
    metadata:
      labels:
        app: ebpf-rust-poc # Ensure this matches the selector.matchLabels
    spec:
      serviceAccountName: ebpf-rust-poc-sa
      hostPID: true # Allow the container to see the host's PID namespace
      containers:
      - name: ebpf-rust-poc-container
        image: ebpf-rust-poc:latest # Use the loaded image from kind
        imagePullPolicy: Never # Use the local image
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - BPF
            - SYSLOG
            - SYS_PTRACE
            - SYS_RESOURCE
            - IPC_LOCK
            - NET_RAW
            - NET_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: bpf
          mountPath: /sys/fs/bpf
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: kind-proc
          mountPath: /proc
          readOnly: true
      volumes:
        - name: bpf
          hostPath:
            path: /sys/fs/bpf
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: kind-proc
          hostPath:
            path: /host-proc
            type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-rust-poc-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebpf-rust-poc-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ebpf-rust-poc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ebpf-rust-poc-role
subjects:
- kind: ServiceAccount
  name: ebpf-rust-poc-sa
  namespace: kube-system